[feat] #113 가게 메뉴 조회(가게 주인) 기능 작성
Booksly/BOOKSLY-SERVER pull request #114
Opened 2024-05-05 10:16 UTC by parkchihoon

## #️⃣연관된 이슈

- close : #113

## 📝작업 내용

가게 전체 메뉴를 조회하는 기능을 작성합니다. (figma 3번)

### request
![스크린샷(56)](https://github.com/Booksly/BOOKSLY-SERVER/assets/127214774/a7dfda83-46dc-4159-a95e-b89c9d9345de)

### response

{
    "status": 200,
    "message": "요청이 성공했습니다.",
    "data": [
        {
            "imgUrl": "imguri1",
            "menuCategory": "남성 컷",
            "menuName": "testMenu1",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "남성 컷",
            "menuName": "testMenu2",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "남성 컷",
            "menuName": "testMenu3",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "여성 컷",
            "menuName": "testMenu4",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "여성 컷",
            "menuName": "testMenu5",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "남성 펌",
            "menuName": "testMenu6",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "남성 펌",
            "menuName": "testMenu7",
            "price": 1000,
            "description": "안녕하세요"
        },
        {
            "imgUrl": "imguri1",
            "menuCategory": "여성 펌",
            "menuName": "testMenu8",
            "price": 1000,
            "description": "안녕하세요"
        }
    ]
}

2024-05-07 00:28 UTC, mungsil requested changes

2024-05-07 00:28 UTC, mungsil commented on src/main/java/kyonggi/bookslyserver/domain/shop/controller/MenuApiController.java
> +    @GetMapping("/api/menu/owner/{shopId}")
restful API 설계에 맞게 /api/shops/{shopId/menus와 같은 API URI는 어떨까요? 다른 URI를 제안하셔도 좋습니다!

2024-05-07 00:28 UTC, mungsil commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +        for(Menu menu : shop.get().getMenus()){
메뉴와 shop의 연관관계를 추가하신 이유가 있을까요?

2024-05-08 05:57 UTC, parkchihoon commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +        for(Menu menu : shop.get().getMenus()){
따로 추가하진 않았습니다. 가게는 여러개의 메뉴를 가질 수 있고, 메뉴 관리 페이지에 들어가게 되면 해당 가게가 가진 메뉴의 리스트를 조회할 수 있게 작성 하였습니다.

2024-05-08 05:59 UTC, merged