Feature/#117 메뉴 카테고리 조회 기능 작성
Booksly/BOOKSLY-SERVER pull request #118
Opened 2024-05-05 14:41 UTC by parkchihoon

## #️⃣연관된 이슈

- close : #117

## 📝작업 내용

메뉴 카테고리 조회 기능을 작성합니다.

### request

![스크린샷(61)](https://github.com/Booksly/BOOKSLY-SERVER/assets/127214774/e79733c6-df23-401f-b509-c60dd01ab148)

### response

![스크린샷(62)](https://github.com/Booksly/BOOKSLY-SERVER/assets/127214774/54b44805-4102-45da-9fda-180a54a00dc3)

2024-05-06 08:56 UTC, mungsil requested changes

2024-05-06 08:56 UTC, mungsil commented on src/main/java/kyonggi/bookslyserver/domain/shop/controller/MenuApiController.java
> +    @GetMapping("/api/menuCategory/owner/{shopId}")
restful한 api URI 설계에 따라, /api/shops/{shopId}/categories와 같은 URI는 어떨까요? 혹은 다른 URI를 사용하셔도 됩니다.  전에 코멘트 남겼던 rest API 설계 링크를 참고하시거나, 구글링을 통해서 관련 내용을 확인해보시면 좋을 것 같습니다.

2024-05-06 08:56 UTC, mungsil commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +            throw new BusinessException(ErrorCode.MENUCATEGORIES_NOT_FOUND);
혹시 카테고리 조회가 아래 사진 등에서 사용되는 기능인가요?
![image](https://github.com/Booksly/BOOKSLY-SERVER/assets/107127451/295a3097-fed1-436c-a78a-f5f76e13655e)
그렇다면 에러 반환 보다 빈 응답을 반환하는게 좋은 설계일 것 같습니다.
 요청 자체는 성공적으로 처리되었으나, 단지 결과가 없다는 것을 의미하기 위해서 빈 응답을 하도록 하는 건 어떨까요?

2024-05-06 08:56 UTC, mungsil commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +        if(shop.get().getMenuCategories() != null){
DB 설계에서 메뉴 카테고리는 가게와 일대다 관계를 가지도록 설계하지 않은 것으로 기억하는데, 다시 코드를 확인해보니 이전에 메뉴 카테고리와 가게 사이 연관관계를 임의로 추가하신 것으로 확인됩니다. 추가하신 이유가 있을까요?
![image](https://github.com/Booksly/BOOKSLY-SERVER/assets/107127451/677bb05e-d77d-4466-ba8e-9af314adba27)
또 DB 설계를 변경하신다면, 이를 다른 팀원 분들에게 변경하였음을 알려주셔야할 뿐만 아니라 ERD도 수정해주셔야합니다.

2024-05-06 08:56 UTC, mungsil commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +            throw new BusinessException(ErrorCode.MENUCATEGORIES_NOT_FOUND);
추가적으로 명세서 작성 시 아래와 같이,
![image](https://github.com/Booksly/BOOKSLY-SERVER/assets/107127451/1cb0e40d-915b-480b-9702-7e97ef9cea31)
해당 api가 사용되는 화면을 함께 올려두시면 좋습니다.

2024-05-08 01:12 UTC, parkchihoon commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +            throw new BusinessException(ErrorCode.MENUCATEGORIES_NOT_FOUND);
카테고리 조회는 위 사진에서 사용되는 기능이 맞습니다. api명세서 작성 시 화면도 함께 등록 하겠습니다.

2024-05-08 01:16 UTC, parkchihoon commented on src/main/java/kyonggi/bookslyserver/domain/shop/service/MenuService.java
> +        if(shop.get().getMenuCategories() != null){
카테고리를 조회 할 때 shop의 id를 받아서 해당 shop이 가지고 있는 메뉴 카테고리를 조회 할 수 있도록 db를 바꿨습니다. erd cloud에 바로 수정하겠습니다.(가게는 여러가지 메뉴 카테고리 항목을 가질 수 있고, 각각의 메뉴 카테고리는 여러가지 메뉴를 가질 수 있도록)

2024-05-08 01:30 UTC, merged